apiVersion: v1
kind: Service
metadata:
  name:  devops03
  labels:
    app: devops03
spec:
  selector:
    app:  devops03
  type:  LoadBalancer
  ports:
    - port:  8080
      targetPort:  80
      nodePort: 31200